name: Morgan Ervin
favicon: null
layout_spectrum: 0.88637
typography_spectrum: 0.64161
title: Morgan Ervin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06090e'
    - '#fefefe'
    - '#f4263c'
    - '#b8bfc2'
    - '#76706a'
  brandStrength: 0.8410373264923692
  lightness: 0.8824300626292825
  saturation: 0.18773981812410057
  rhythmicContrast: 0.9945216595660895
purpose: []
